### ISSUE TITLE
Add sower to gen3_tracker/collaborator/access/policies/add-user-write.yaml

### ISSUE THREAD

**Issue by bwalsh** [ACED-IDP/gen3_util#121]
```
policies:
# submitter policy
- policy_id: programs.PROGRAM.projects.PROJECT_writer
  username:

# data uploader
- policy_id: data_upload
  username:

# gateway writer
- policy_id: mds_gateway
  username:

# sower writer
- policy_id: sower
  username:
```
