### ISSUE TITLE
edit metadata

### ISSUE THREAD

**Issue by bwalsh** [ACED-IDP/gen3_util#29]
### Background: 

  * [end to end overview]( https://www.websequencediagrams.com/cgi-bin/cdraw?lz=dGl0bGUgQUNFRCBNZXRhZGF0YSBpbnRlZ3JhdGlvbgoKIyBvcHRpb24gZm9vdGVyPW5vbmUKCmFjdG9yIERhdGFBY2Nlc3NDb21pdHRlZQASB1Jlc2VhcmNoZXIKCmFsdCAAUgVhACUFIGFnZ3JlZW1lbnQKAB0KLT4rADsSOiBhcHBseQoAVRItLT4tAFoKOiBvawplbmQKCiMgbm90ZSBvdmVyIGdlbjNfdXRpbCxnZW4zLWNsaWVudDogAAIGACIIbGVmdCBvZiBhY2VkLWlkcC5yZXF1ZXN0b3I6IHNlcnYAgTkIc2V0dXAAgSIOAFcJOiBpbnN0YWxsCgBqCQCBDRMAKxEAgQkJADIMAIEgBwATLWNvbmZpZwAgHwCCGgUAgwcGcHJvamVjdC1jcmUAg14GAIE_GAAiByBuZXcAgVALPisAghkUbmV3IACCNQcKAII7Ei0tPi0AgiULAIJeByhzKQCCFh0Ag2UUAIJrDXNpZ24ANxYAgQ8Wc2lnbmVkAHMMAIEYEwCBVQthcmJvcmlzdDogdXBkYXRlIGF1dGhvcml6AIYWBgAXES0tPi0AhDYUb2sAgXIib2sAhDEOAIV7FACDPwlhbHQgYWRkLWZpbGVzAIR-GW1hbmlmZXN0IHB1dCBmaWxlAIUEHQCGPAVhbHQgdXBsb2EAMykAKAYAhAoWaW5kZXhkOiAAhGUFZQB-BSAADwUgcmVjb3JkcwCEIQoAJQYAgXgcAIRtC2ZlbmNlOiBnZQCBUQYAg1AIdXJsAIRyCgAfBQCEaQ8AHQsAhUULAIgSDQCBdwYAgjIJAIcIDT4rYW55LmJ1Y2tlACAKAIFQBXRvAHcNAB0JAIVwCACIdQkAg18HAIdcCwCIPQpvawoKb3B0AIInBy1tAIsIBwCBGxAAg1UIaW5pbXVtIGdyYXBoAIcTDACCVSkAgWSBGQCFIgkAgg9qAIlKFXNvd2VyOiBydW5fam9iIGltcG9ydC1maGlyAIlZCgAfBQCHORIAjQoFAIZNIW9wdACIUwcAg2QKAIN-BWdldACDdgoAjF4YZ2V0IACEERQAgSgZZXhwb3J0XwCBHCUAhggYZG93AIMAJGRvd24AhkQFAIJPTwCCLhtlZGkAghIjdG9fdGFibHVhcgCPER0AkEIFcmlnaACQGQUAkF8MAJIVCGVzIHN0dWR5AJFWBgoAkAMZZnJvbQBOJQCECQlwdWJsaXNoAINSCgCPBxkAIwYAhGxRAIwFIQoKCg&s=qsd)

  * [edit metadata](https://www.websequencediagrams.com/cgi-bin/cdraw?lz=dGl0bGUgQUNFRCBNZXRhZGF0YQoKYWN0b3IgUmVzZWFyY2hlcgpwYXJ0aWNpcGFudCBnZW4zX3V0aWwABREtY2xpZW50CgpvcHQgdXBkYXRlLW0ATAkAEQVnZXQACQpub3RlIHJpZ2h0IG9mAGQLOiBhZnRlciB1cGxvYWRpbmcgZmlsZXMKAIEHCi0-KwB-CTogZ2V0IABfCQCBFgktPithY2VkLWlkcC5zb3dlcjogcnVuX2pvYiBleHBvcnRfZmhpcgB2DwAiEGdldCBhbGwAVgkgZm9yIHByb2plY3QKAFEOLT5hbnkuYnVja2V0OgCBNQcALgp0bwCBQAUAJBAtPi0AgT4Lb2sAgTINAIJJCzogZG93AE0FAEEFAIJjCy0-KwBsDGRvd24AdQVzaWduZWQgdXJsCgCBDgoAaAgATQkAawcARAgAgQINAIEBDS0-LQCDFQxvawplbmQKAIMoG0ZISVIgAIIuBQCBCwhlZACDfgdlZGkAg2ElaW50ZWdyYXRlcyBzdHVkeQBJBgCDbhl0b190YWJsdWFyAINvFnB1YmxpY18AgxoIZ2V0X2NvbmZpZ3VyYXRpb24gZGVmYXVsdChwcm9ncmFtLACDYQgpAINgCgA3DQCDLw8ARwYAhScFKHtyZXNvdXJjZTogW2NvbHVtbi1saXN0XX0pID0ATRsAhTILAIVVC2ZsYXR0ZW4AhiEPABUMb3IgZWFjaCAAZQYgaW4AAwcAcAU6IHdyaXRlXwCBAgYAgzcdAIZKGWZyb20AgTqBJACCKxdpbXBvcnQgW3RzdiwgeGxzXQCCUxd1bi0AgixBcmVhZACCZQcsAIl_ByBmaGlyLQCECwgAg08XAIMgBQAlBQCGOzwAhWAFc2gAigsFAIZ6BQoK&s=default)

### Edit Metadata

![image](https://github.com/ACED-IDP/gen3_util/assets/47808/b615fb43-9af8-48e0-ac64-74563efc45cb)

**Comment by bwalsh** [comment]
See tests/unit/tabular/README.md for complete design writeup

**Comment by bwalsh** [comment]
```yaml
configuration:
  default:
    Patient: [flattened column names]
    Specimen: [flattened column names]
    Observation: [flattened column names]
    ResearchStudy: [flattened column names]
    ResearchSubject: [flattened column names]
 <program>:
    # defaults for a program go here 
 <program-project>:
    # defaults for a program-project go here 

```
