### ISSUE TITLE
improve empty project

### ISSUE THREAD

**Issue by bwalsh** [ACED-IDP/gen3_util#57]
As an aced data submitter, when I empty all content from the project, the .g3t/state should be cleared

Although the etl pod now has a [empty project capability](https://github.com/ACED-IDP/aced_etl_pod/pull/25), several improvements could be made:

* move the feature from [g3t utilities projects empty](https://github.com/ACED-IDP/gen3_util/pull/53) to a new, top level command, perhaps `g3t reset`
* add fhir_delete to [aced_submission](https://github.com/ACED-IDP/submission/blob/feature/empty-project/aced_submission/fhir_store.py)

**Comment by matthewpeterkort** [comment]
addressed in:
https://github.com/ACED-IDP/gen3_util/pull/56
https://github.com/ACED-IDP/submission/pull/17
https://github.com/ACED-IDP/aced_etl_pod/pull/25

note: In order for the delete permissions to take effect you will need to create a seperate 'deleter' role in user.yaml
```
- description: ''
    id: deleter
    permissions:
    - action:
        method: delete
        service: '*'
      constraints: {}
      description: ''
      id: deleter
```
and then run a `kc delete job/user-yaml` followed by a `make local`

and then remove delete permissions from the writer role. 

Then gaining delete permissions can be done with a g3t --profile local utilities access add --roles deleter
type command.
